### PR TITLE
Created ReverseDeskCroc

### PR DESCRIPTION
**Pull request by 0iphor13**
Want screen access and full remote control over your target?
Don't have access to a ScreenCrab?

Then RemoteDeskCroc is your payload! Get screen access! 🐊

### CODE REVIEW

**Comment by hak5darren** [comment]
Another wonderful payload. Thanks @0iphor13 
Please find our token of appreciation at https://rewards.hak5.org

**Comment by 0iphor13** [comment]
> Another wonderful payload. Thanks @0iphor13 Please find our token of appreciation at https://rewards.hak5.org

I recieved no new reward :(

**Comment by hak5darren** [comment]
Strange. Maybe I made a typo in the reward. Can you check https://rewards.hak5.org again now?

**Comment by 0iphor13** [comment]
> Strange. Maybe I made a typo in the reward. Can you check https://rewards.hak5.org again now?

@hak5darren This time it's there, maybe there's another Oiphorie now, wondering why he's got a reward code :-D
Anyways, thanks a lot <3

**Pull request merged**
